# Gradle
org.gradle.jvmargs=-Xmx6g -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# Kotlin
kotlin.code.style=official
kotlin.daemon.jvmargs=-Xmx6g

# Android
android.useAndroidX=true

# VS Core
ru.vs.core.useVsCoreSources=true
ru.vs.core.version=1.9.0
ru.vs.basePackage=ru.vladislavsumin

# VS QA
ru.vs.qa.composeStabilityAnalyzer.enabled=false
ru.vs.qa.composeStabilityAnalyzer.traceAll=false
