name: CI

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:
    inputs:
      use-vs-core-sources:
        description: 'Use vs-core sources instead of Maven artifacts'
        type: boolean
        default: false

jobs:
  detekt:
    name: Run detekt
    runs-on: ubuntu-24.04
    timeout-minutes: 15
    steps:
      - name: Clone vs-qa repository
        uses: actions/checkout@v4
        with:
          path: vs-qa

      - name: Clone vs-core repository
        if: inputs.use-vs-core-sources == 'true'
        uses: actions/checkout@v4
        with:
          repository: VladislavSumin/vs-core
          path: vs-core

      - name: Run gradle
        uses: ./vs-qa/.github/actions/run_gradle_default
        with:
          key: "detekt"
          gradle_command: >-
            -Pru.vs.core.useVsCoreSources=${{ inputs.use-vs-core-sources || 'false' }}
            detekt

  unit-tests:
    name: unit tests
    runs-on: macos-15
    timeout-minutes: 45
    steps:
      - name: Clone vs-qa repository
        uses: actions/checkout@v4
        with:
          path: vs-qa

      - name: Clone vs-core repository
        if: inputs.use-vs-core-sources == 'true'
        uses: actions/checkout@v4
        with:
          repository: VladislavSumin/vs-core
          path: vs-core

      - name: Run gradle
        uses: ./vs-qa/.github/actions/run_gradle_default
        with:
          key: "unit-tests"
          gradle_command: >-
            -Pru.vs.core.useVsCoreSources=${{ inputs.use-vs-core-sources || 'false' }}
            test allTests

  build:
    name: build app
    runs-on: macos-15
    timeout-minutes: 45
    steps:
      - name: Clone vs-qa repository
        uses: actions/checkout@v4
        with:
          path: vs-qa

      - name: Clone vs-core repository
        if: inputs.use-vs-core-sources == 'true'
        uses: actions/checkout@v4
        with:
          repository: VladislavSumin/vs-core
          path: vs-core

      - name: Run gradle
        uses: ./vs-qa/.github/actions/run_gradle_default
        with:
          key: "build"
          gradle_command: >-
            -Pru.vs.core.useVsCoreSources=${{ inputs.use-vs-core-sources || 'false' }}
            :app:jvm:buildFatJarMain 
            :app:jvm:buildFatJarMainMin
            :app:android:assembleRelease

      - name: Upload jar
        uses: actions/upload-artifact@v4
        with:
          name: vs-qa.jar
          path: ./vs-qa/app/jvm/build/libs/vs-qa.jar

      - name: Upload jar-min
        uses: actions/upload-artifact@v4
        with:
          name: vs-qa-min.jar
          path: ./vs-qa/app/jvm/build/libs/vs-qa-min.jar

      - name: Upload app-release.apk
        uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: ./vs-qa/app/android/build/outputs/apk/release/app-release.apk
